# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku040-ffva1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.cache/wt} [current_project]
set_property parent.project_path {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/imports/new/adc_board.v}
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/imports/new/adc_spi.v}
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/arp_cache.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/arp_rx.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/arp_tx.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/crc.v
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/imports/new/data_package.v}
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/imports/new/data_processing.v}
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/imports/new/data_sample.v}
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/new/ethernet.v}
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/new/ethernet_test.v}
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/new/gmii_arbi.v}
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/gmii_rx_buffer.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/gmii_tx_buffer.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/icmp_reply.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/ip_rx.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/ip_tx.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/ip_tx_mode.v
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/imports/new/lut_config.v}
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/mac_rx.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/mac_rx_top.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/mac_test.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/mac_top.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/mac_tx.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/mac_tx_mode.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/mac_tx_top.v
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/imports/src/sd_card/sd_card_cmd.v}
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/imports/src/sd_card/sd_card_sec_read_write.v}
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/imports/src/sd_card_test.v}
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/imports/src/sd_card/sd_card_top.v}
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/smi_config.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/smi_read_write.v
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/imports/new/spi_config.v}
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/imports/new/spi_master.v}
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/udp_rx.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/udp_tx.v
  C:/Users/DELL/Desktop/CW4.team/adc_ethernet_v3.1.1/adc_ethernet/adc_ethernet.srcs/sources_1/new/util_gmii_to_rgmii.v
  {C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/new/top_1.v}
}
read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/sys_clk_mmcm/sys_clk_mmcm.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/sys_clk_mmcm/sys_clk_mmcm_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/sys_clk_mmcm/sys_clk_mmcm.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/sys_clk_mmcm/sys_clk_mmcm_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo3/fifo3.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo3/fifo3.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo3/fifo3_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo2/fifo2.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo2/fifo2.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo2/fifo2_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo4/fifo4.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo4/fifo4.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo4/fifo4_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo_ttt/fifo_ttt.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo_ttt/fifo_ttt.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo_ttt/fifo_ttt_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_0/ila_0.xci}}
set_property used_in_synthesis false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_1/ila_1.xci}}
set_property used_in_synthesis false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_2/ila_2.xci}}
set_property used_in_synthesis false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_2/ila_2_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_3/ila_3.xci}}
set_property used_in_synthesis false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_3/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_3/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_3/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_3/ila_3_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_4/ila_4.xci}}
set_property used_in_synthesis false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_4/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_4/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_4/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_4/ila_4_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo5/fifo5.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo5/fifo5.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo5/fifo5_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/fifo5/fifo5_clocks.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/eth_data_fifo/eth_data_fifo_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/len_fifo/len_fifo.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/len_fifo/len_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/len_fifo/len_fifo_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_5/ila_5.xci}}
set_property used_in_synthesis false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_5/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_5/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_5/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_5/ila_5_ooc.xdc}}]

read_ip -quiet {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_6/ila_6.xci}}
set_property used_in_synthesis false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_6/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_6/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_6/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/sources_1/ip/ila_6/ila_6_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/constrs_1/imports/new/adc_ethernet.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/DELL/Desktop/CW4.team/adc_8channel V2/adc_8channel_sd_eth_1600_v1/adc_8channel/adc_8channel.srcs/constrs_1/imports/new/adc_ethernet.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xcku040-ffva1156-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
